### ISSUE TITLE
Feature labels of vertices in features?

### ISSUE THREAD

**Issue by spectraldecomp** [hpgem/nanomesh#297] opened 2024-06-25 20:53 UTC
I use `classes = m.point_data['gmsh:physical']` to get the class labels of each point in my mesh, but only the vertices on the boundaries/contour of each feature are labeled. Is there a way to have the points in the inner region of each boundary be labeled accordingly?

**Comment by stefsmeets** [comment] 2024-07-08 07:19
You could use the point data to decide whether a vertex is inside or outside. There is no 'automatic' way of doing it atm.

**Comment by spectraldecomp** [comment] 2024-07-08 14:45
It seems like `point_data['gmsh:physical']` assigns labels according to the contour of the feature and not the interior of the feature.

I.e. 
![image](https://github.com/hpgem/nanomesh/assets/98125550/42f89e72-8323-45c4-a95e-f8d516314e73)

When what we might expect is 
![image](https://github.com/hpgem/nanomesh/assets/98125550/19172df1-fb84-41f2-8b3a-d94c58543d1c)

Is this the intended behavior?

I have a temporary solution to get nearly the latter behavior by using `cell_data_dict['gmsh:physical']['triangle']` and assigning labels according to the triangle each point belongs.

**Comment by stefsmeets** [comment] 2024-07-09 09:30
Hi @spectraldecomp Actually, on second thought, yes that is the intended behaviour. The code finds the interfaces, not the points inside a region. In your second example, you could not know if the edge vertices are inside, or outside the region.

The better way to approach this is to use the `mesh.cell_data`, and use that as a mask on the vertices (`mesh.points`). This will give you the points inside or outside the regions as in your second figure.

**Comment by stefsmeets** [comment] 2024-10-01 07:35
I'm going to close this issue, but feel to re-open a new one if you have any further questions!

**Closed as completed by stefsmeets** 2024-10-01 07:35 UTC
